### ISSUE TITLE
Suggestion: make it so that we can download instant installers/direct-apps based on the os

### ISSUE THREAD

**Issue by Advik-B** [Griphcode/Griphitor-IDE#2]
So.... here is the thing:

Why do we have to clone AND Install node AND build instead of directly downloading it.

this is just a suggestion. I would Love to see open-source projects grow

**Comment by Griphcode** [comment]
Thank for your Feedback this is what we are currently working on thanks for giving us new feedback.

**Comment by oxmc** [comment]
@Advik-B Working on it now...

**Comment by oxmc** [comment]
@Advik-B Got Windows release done.

**Comment by oxmc** [comment]
You can download Griphitor based on your OS at: https://griphitor.xyz
